### ISSUE TITLE
treetable 使用分页切换时出现错误

### ISSUE THREAD

**Issue by ArthurSec** [layui/layui#2056]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

v2.9.13

### 问题描述

使用静态数据渲染treetable之后切换分页时第二页及往后页无法显示叶子节点
控制台报错
treeTable.js:1080 Uncaught 
TypeError: Cannot read properties of undefined (reading 'LAY_EXPAND')
    at HTMLTableCellElement.<anonymous> (treeTable.js:1080:60)
    at n (layui.js:602:17)
    at n.each (layui.js:611:12)
    at a.renderTreeTable (treeTable.js:1068:11)
    at a.done (treeTable.js:221:14)
    at c (table.js:1139:53)
    at n.pullData (table.js:1247:7)
    at Object.jump (table.js:1528:18)
    at t.render (laypage.js:314:27)
    at HTMLAnchorElement.<anonymous> (laypage.js:247:16)

测试数据使用官网treetable示例数据 [https://layui.dev/static/json/2/treeTable/demo-1.json](url)

### 业务代码

```auto
layui.use(function(){
    var treeTable = layui.treeTable;
    var layer = layui.layer;
    var data = `[
        {
            "id": 1,
            "name": "User-1",
            "type": 4,
            "status": 2,
            "score": 28,
            "experience": 54981,
            "sex": "男",
            "city": "丽江市",
            "description": "-",
            "createTime": "2014-06-04 12:29:55",
            "parentId": null,
            "children": [
                {
                    "id": 2,
                    "name": "User-2",
                    "type": 2,
                    "status": 3,
                    "score": 75,
                    "experience": 43884,
                    "sex": "女",
                    "city": "大理白族自治州",
                    "description": "-",
                    "createTime": "1971-11-03 19:15:43",
                    "parentId": null,
                    "children": [
                    
                    ],
                    "isParent": true
                }
            ],
            "isParent": true
        },
        {
            "id": 9,
            "name": "User-9",
            "type": 6,
            "status": 2,
            "score": 58,
            "experience": 2414,
            "sex": "女",
            "city": "宿州市",
            "description": "-",
            "createTime": "2015-05-06 00:39:19",
            "parentId": null,
            "children": [],
            "isParent": false
        },
        {
            "id": 10,
            "name": "User-10",
            "type": 4,
            "status": 2,
            "score": 89,
            "experience": 97592,
            "sex": "女",
            "city": "钦州市",
            "description": "-",
            "createTime": "1985-05-26 03:50:09",
            "parentId": null,
            "children": [
            
            ],
            "isParent": true
        },
        {
            "id": 70,
            "name": "User-70",
            "type": 3,
            "status": 3,
            "score": 19,
            "experience": 66961,
            "sex": "女",
            "city": "固原市",
            "description": "-",
            "createTime": "1992-04-11 09:13:05",
            "parentId": null,
            "children": [],
            "isParent": false
        },
        {
            "id": 71,
            "name": "User-71",
            "type": 1,
            "status": 3,
            "score": 4,
            "experience": 95553,
            "sex": "女",
            "city": "那曲地区",
            "description": "-",
            "createTime": "2019-07-31 00:30:49",
            "parentId": null,
            "children": [
                {
                    "id": 72,
                    "name": "User-72",
                    "type": 4,
                    "status": 4,
                    "score": 89,
                    "experience": 27410,
                    "sex": "男",
                    "city": "贺州市",
                    "description": "-",
                    "createTime": "1990-09-07 03:02:32",
                    "parentId": null,
                    "children": [
                        {
                            "id": 73,
                            "name": "User-73",
                            "type": 6,
                            "status": 4,
                            "score": 93,
                            "experience": 84018,
                            "sex": "男",
                            "city": "雅安市",
                            "description": "-",
                            "createTime": "1972-01-18 02:00:25",
                            "parentId": null,
                            "children": [
                                {
                                    "id": 74,
                                    "name": "User-74",
                                    "type": 1,
                                    "status": 4,
                                    "score": 22,
                                    "experience": 23025,
                                    "sex": "女",
                                    "city": "济南市",
                                    "description": "-",
                                    "createTime": "1991-12-18 23:27:07",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                },
                                {
                                    "id": 75,
                                    "name": "User-75",
                                    "type": 5,
                                    "status": 2,
                                    "score": 75,
                                    "experience": 58006,
                                    "sex": "男",
                                    "city": "新界",
                                    "description": "-",
                                    "createTime": "2004-03-03 09:28:00",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                }
                            ],
                            "isParent": true
                        }
                    ],
                    "isParent": true
                },
                {
                    "id": 76,
                    "name": "User-76",
                    "type": 2,
                    "status": 1,
                    "score": 79,
                    "experience": 86538,
                    "sex": "男",
                    "city": "果洛藏族自治州",
                    "description": "-",
                    "createTime": "2000-02-09 12:26:36",
                    "parentId": null,
                    "children": [
                    
                    ],
                    "isParent": true
                },
                {
                    "id": 88,
                    "name": "User-88",
                    "type": 4,
                    "status": 2,
                    "score": 65,
                    "experience": 38077,
                    "sex": "女",
                    "city": "黄石市",
                    "description": "-",
                    "createTime": "2007-12-12 15:47:51",
                    "parentId": null,
                    "children": [
                        {
                            "id": 89,
                            "name": "User-89",
                            "type": 6,
                            "status": 2,
                            "score": 78,
                            "experience": 78006,
                            "sex": "男",
                            "city": "海口市",
                            "description": "-",
                            "createTime": "2007-10-20 18:46:39",
                            "parentId": null,
                            "children": [],
                            "isParent": false
                        },
                        {
                            "id": 90,
                            "name": "User-90",
                            "type": 3,
                            "status": 3,
                            "score": 66,
                            "experience": 91901,
                            "sex": "女",
                            "city": "上海市",
                            "description": "-",
                            "createTime": "1993-08-25 20:32:32",
                            "parentId": null,
                            "children": [],
                            "isParent": false
                        }
                    ],
                    "isParent": true
                }
            ],
            "isParent": true
        },
        {
            "id": 91,
            "name": "User-91",
            "type": 3,
            "status": 3,
            "score": 61,
            "experience": 26129,
            "sex": "女",
            "city": "白山市",
            "description": "-",
            "createTime": "2002-01-04 16:12:16",
            "parentId": null,
            "children": [
            
            ],
            "isParent": true
        },
        {
            "id": 138,
            "name": "User-138",
            "type": 1,
            "status": 2,
            "score": 99,
            "experience": 71832,
            "sex": "男",
            "city": "阿里地区",
            "description": "-",
            "createTime": "1988-03-10 13:17:59",
            "parentId": null,
            "children": [
                {
                    "id": 139,
                    "name": "User-139",
                    "type": 6,
                    "status": 4,
                    "score": 36,
                    "experience": 86381,
                    "sex": "女",
                    "city": "菏泽市",
                    "description": "-",
                    "createTime": "2021-04-22 22:27:06",
                    "parentId": null,
                    "children": [
                    ],
                    "isParent": true
                },
                {
                    "id": 156,
                    "name": "User-156",
                    "type": 4,
                    "status": 2,
                    "score": 79,
                    "experience": 99919,
                    "sex": "女",
                    "city": "凉山彝族自治州",
                    "description": "-",
                    "createTime": "2010-07-15 10:21:19",
                    "parentId": null,
                    "children": [
                        {
                            "id": 157,
                            "name": "User-157",
                            "type": 5,
                            "status": 3,
                            "score": 91,
                            "experience": 52354,
                            "sex": "男",
                            "city": "铜仁市",
                            "description": "-",
                            "createTime": "1977-03-20 09:15:54",
                            "parentId": null,
                            "children": [],
                            "isParent": false
                        },
                        {
                            "id": 158,
                            "name": "User-158",
                            "type": 5,
                            "status": 2,
                            "score": 22,
                            "experience": 51977,
                            "sex": "女",
                            "city": "宿州市",
                            "description": "-",
                            "createTime": "2016-11-17 20:01:17",
                            "parentId": null,
                            "children": [],
                            "isParent": false
                        }
                    ],
                    "isParent": true
                },
                {
                    "id": 159,
                    "name": "User-159",
                    "type": 1,
                    "status": 2,
                    "score": 43,
                    "experience": 46650,
                    "sex": "女",
                    "city": "沧州市",
                    "description": "-",
                    "createTime": "1987-09-05 06:14:08",
                    "parentId": null,
                    "children": [],
                    "isParent": false
                },
                {
                    "id": 160,
                    "name": "User-160",
                    "type": 6,
                    "status": 2,
                    "score": 57,
                    "experience": 7416,
                    "sex": "男",
                    "city": "澎湖县",
                    "description": "-",
                    "createTime": "1974-08-10 20:09:38",
                    "parentId": null,
                    "children": [
                        {
                            "id": 161,
                            "name": "User-161",
                            "type": 5,
                            "status": 1,
                            "score": 53,
                            "experience": 12421,
                            "sex": "男",
                            "city": "阿克苏地区",
                            "description": "-",
                            "createTime": "1998-02-07 11:52:05",
                            "parentId": null,
                            "children": [
                                {
                                    "id": 162,
                                    "name": "User-162",
                                    "type": 3,
                                    "status": 2,
                                    "score": 100,
                                    "experience": 19507,
                                    "sex": "女",
                                    "city": "随州市",
                                    "description": "-",
                                    "createTime": "2014-01-31 07:58:18",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                },
                                {
                                    "id": 163,
                                    "name": "User-163",
                                    "type": 2,
                                    "status": 2,
                                    "score": 12,
                                    "experience": 35637,
                                    "sex": "男",
                                    "city": "拉萨市",
                                    "description": "-",
                                    "createTime": "1983-10-02 10:31:23",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                },
                                {
                                    "id": 164,
                                    "name": "User-164",
                                    "type": 6,
                                    "status": 3,
                                    "score": 65,
                                    "experience": 42198,
                                    "sex": "男",
                                    "city": "香港岛",
                                    "description": "-",
                                    "createTime": "1987-12-22 14:34:32",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                }
                            ],
                            "isParent": true
                        }
                    ],
                    "isParent": true
                },
                {
                    "id": 165,
                    "name": "User-165",
                    "type": 2,
                    "status": 2,
                    "score": 73,
                    "experience": 40495,
                    "sex": "女",
                    "city": "天津市",
                    "description": "-",
                    "createTime": "1992-11-29 08:54:58",
                    "parentId": null,
                    "children": [
                        {
                            "id": 166,
                            "name": "User-166",
                            "type": 3,
                            "status": 3,
                            "score": 83,
                            "experience": 62007,
                            "sex": "男",
                            "city": "重庆市",
                            "description": "-",
                            "createTime": "1992-10-01 19:14:47",
                            "parentId": null,
                            "children": [
                                {
                                    "id": 167,
                                    "name": "User-167",
                                    "type": 5,
                                    "status": 4,
                                    "score": 75,
                                    "experience": 18137,
                                    "sex": "女",
                                    "city": "安顺市",
                                    "description": "-",
                                    "createTime": "2011-10-10 19:40:42",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                },
                                {
                                    "id": 168,
                                    "name": "User-168",
                                    "type": 4,
                                    "status": 3,
                                    "score": 80,
                                    "experience": 95421,
                                    "sex": "男",
                                    "city": "吴忠市",
                                    "description": "-",
                                    "createTime": "1972-10-27 14:58:59",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                },
                                {
                                    "id": 169,
                                    "name": "User-169",
                                    "type": 6,
                                    "status": 3,
                                    "score": 10,
                                    "experience": 2784,
                                    "sex": "男",
                                    "city": "伊春市",
                                    "description": "-",
                                    "createTime": "1992-07-06 23:16:42",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                },
                                {
                                    "id": 170,
                                    "name": "User-170",
                                    "type": 5,
                                    "status": 3,
                                    "score": 68,
                                    "experience": 54101,
                                    "sex": "男",
                                    "city": "贺州市",
                                    "description": "-",
                                    "createTime": "1970-01-21 21:50:15",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                }
                            ],
                            "isParent": true
                        }
                    ],
                    "isParent": true
                }
            ],
            "isParent": true
        },
        {
            "id": 271,
            "name": "User-271",
            "type": 4,
            "status": 2,
            "score": 24,
            "experience": 42013,
            "sex": "女",
            "city": "宝鸡市",
            "description": "-",
            "createTime": "2013-10-19 09:10:48",
            "parentId": null,
            "children": [
                {
                    "id": 272,
                    "name": "User-272",
                    "type": 5,
                    "status": 4,
                    "score": 7,
                    "experience": 86631,
                    "sex": "男",
                    "city": "黄石市",
                    "description": "-",
                    "createTime": "1983-02-15 19:44:19",
                    "parentId": null,
                    "children": [
                        {
                            "id": 273,
                            "name": "User-273",
                            "type": 5,
                            "status": 1,
                            "score": 5,
                            "experience": 90121,
                            "sex": "女",
                            "city": "淮安市",
                            "description": "-",
                            "createTime": "1986-05-10 21:35:11",
                            "parentId": null,
                            "children": [
                                {
                                    "id": 274,
                                    "name": "User-274",
                                    "type": 1,
                                    "status": 3,
                                    "score": 97,
                                    "experience": 74832,
                                    "sex": "男",
                                    "city": "四平市",
                                    "description": "-",
                                    "createTime": "1996-08-04 00:38:03",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                },
                                {
                                    "id": 275,
                                    "name": "User-275",
                                    "type": 2,
                                    "status": 2,
                                    "score": 42,
                                    "experience": 45129,
                                    "sex": "男",
                                    "city": "昌都地区",
                                    "description": "-",
                                    "createTime": "1983-01-14 21:58:01",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                }
                            ],
                            "isParent": true
                        },
                        {
                            "id": 276,
                            "name": "User-276",
                            "type": 4,
                            "status": 3,
                            "score": 2,
                            "experience": 40565,
                            "sex": "女",
                            "city": "普洱市",
                            "description": "-",
                            "createTime": "1998-03-28 19:05:33",
                            "parentId": null,
                            "children": [
                                {
                                    "id": 277,
                                    "name": "User-277",
                                    "type": 2,
                                    "status": 1,
                                    "score": 6,
                                    "experience": 27426,
                                    "sex": "男",
                                    "city": "安顺市",
                                    "description": "-",
                                    "createTime": "2023-01-17 10:34:05",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                },
                                {
                                    "id": 278,
                                    "name": "User-278",
                                    "type": 4,
                                    "status": 2,
                                    "score": 36,
                                    "experience": 22014,
                                    "sex": "男",
                                    "city": "榆林市",
                                    "description": "-",
                                    "createTime": "1993-01-12 09:41:01",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                },
                                {
                                    "id": 279,
                                    "name": "User-279",
                                    "type": 4,
                                    "status": 1,
                                    "score": 43,
                                    "experience": 35756,
                                    "sex": "女",
                                    "city": "天津市",
                                    "description": "-",
                                    "createTime": "2002-03-20 11:28:25",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                },
                                {
                                    "id": 280,
                                    "name": "User-280",
                                    "type": 2,
                                    "status": 3,
                                    "score": 94,
                                    "experience": 59280,
                                    "sex": "女",
                                    "city": "松原市",
                                    "description": "-",
                                    "createTime": "2008-09-28 10:43:16",
                                    "parentId": null,
                                    "children": [],
                                    "isParent": false
                                }
                            ],
                            "isParent": true
                        }
                    ],
                    "isParent": true
                }
            ],
            "isParent": true
        }
        
    ]`;

    // 渲染
    var inst = treeTable.render({
        elem: '#ID-treeTable-demo',
        data: JSON.parse(data),
        maxHeight: '501px',
        toolbar: '#TPL-treeTable-demo',
        cols: [[
            {type: 'checkbox', fixed: 'left'},
            {field: 'id', title: 'ID', width: 80, sort: true, fixed: 'left'},
            {field: 'name', title: '用户名', width: 180, fixed: 'left'},
            {field: 'sex', title: '性别', width: 80, sort: true},
            {field: 'experience', title: '积分', width: 90, sort: true},
            {field: 'city', title: '城市', width: 100},
            { fixed: "right", title: "操作", width: 190, align: "center", toolbar: "#TPL-treeTable-demo-tools"}
        ]],
        page: true,
        limit: 3
    });
    // 表头工具栏工具事件
    treeTable.on("toolbar(ID-treeTable-demo)", function (obj) {
        var config = obj.config;
        var tableId = config.id;
        var status = treeTable.checkStatus(tableId);
        // 获取选中行
        if (obj.event === "getChecked") {
            if(!status.data.length) return layer.msg('无选中数据');
            console.log(status);
            layer.alert("当前数据选中已经输出到控制台，<br>您可按 F12 从控制台中查看结果。");
        }
    });
});
```

### 截图补充

![QQ截图20240624160551](https://github.com/layui/layui/assets/25519378/11395f6a-055e-4f00-8401-bb1a91d0a01c)

### 浏览器

chrome 126.0.6478.61

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Sight-wcg** [comment]
2.8.16 中出现的问题，ref c9d67979f506a37ac69d3ecb1215b22a360460d0

**Comment by kerwin1015** [comment]
![5567](https://github.com/user-attachments/assets/9c9f5781-b666-41da-ab83-23ed0f066e80)
2.9.14还是有这个问题
