### ISSUE TITLE
2.9.13 Tree组件获取checked节点提示错误

### ISSUE THREAD

**Issue by Tarems** [layui/layui#2156]
### 议题条件

- [X] 我确认已查看官方使用文档：https://layui.dev ，但没有找到相关解决方案。
- [X] 我确认已在 [Issues](https://github.com/layui/layui/issues?q=is%3Aissue ) 中搜索过类似的问题，但没有找到相关解决方案。
- [X] 我已仔细阅读： 🍀[ Layui Issue 贡献指南](https://github.com/layui/layui/blob/main/CONTRIBUTING.md)

### 议题类型

疑是 BUG

### 使用版本

2.9.13

### 问题描述

使用 tree.getChecked('grid_tree')
layui.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getChecked')
    at t.getChecked (layui.js:1:341682)
    at HTMLAnchorElement.addGridPeople (index:136:34)
    at n.on.e.<computed> (layui.js:1:193761)
    at HTMLBodyElement.dispatch (layui.js:1:106542)
    at h.handle (layui.js:1:103293)
t

### 业务代码

```auto
tree.render({
                elem: '#grid_tree',
                data: data,
                showLine: false,  // 是否开启连接线
                showCheckbox: true,
                click: function (obj) {
                    console.log(obj.data); // 得到当前点击的节点数据
                    console.log(obj.state); // 得到当前节点的展开状态：open、close、normal
                    console.log(obj.elem); // 得到当前节点元素
                    console.log(obj.data.children); // 当前节点下是否有子节点
                    tree.setChecked('grid_tree', [obj.data.id]);
                    gridDepartId_ = obj.data.id;
                    tree.getChecked('grid_tree')
                }
            });
```

### 浏览器

谷歌最新版

### 友好承诺

- [X] 我承诺将本着相互尊重、理解和友善的态度进行交流，共同维护 Layui 良好的社区氛围。

**Comment by Tarems** [comment]
我个人问题,没有加上id: 'grid_tree' 导致的
